name: waffensachkunde_app
description: Learn for the Waffensachkunde

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  styled_widget: ^0.4.1
  tuple: ^2.0.2
  file_saver: ^0.2.9
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/questions.json
